train:
  model_name: UIENet
  task_name: base
  save_dir: ./log
  seed: 42
  max_epochs: 300
  valid_frequency: 1
  ckpt_name: last

optim:
  lr_init: 2e-4
  lr_min: 1e-6
  warmup_epochs: 5
  weight_decay: 1e-8

data:
  train_path: "/workspace/Lianghui/dataset/UIEB/train/"
  train_batch_size: 8
  train_img_size: 256
  valid_path: "/workspace/Lianghui/dataset/UIEB/val/"
  valid_batch_size: 1
  valid_img_size: 256
  num_workers: 1
  pin_memory: True